@startuml EducationPlatformDomain

class Itinerary {
    - custom : boolean
    + Edit()
}

abstract Topic{
    + getTableOfContents()
    + getSyllabus() : Concepts
    + Edit()
    + Read()
}


class SimpleTopic{
}

class CompositeTopic{
    - topics : List<Topic> 
}

abstract Excercise {
}

class Domain {
}

class Application {
    - correct : boolean
    - evaluated: boolean
    - Version
}

class Question {
    - statement : StatementType
}

enum StatementType {
    ClozeTest
    Definition
    Relation
    JustifyApplication
}

class Text {
    - tableOfContents
    - images
}

class Concept {
}

class Definition {
    - correct : boolean
}

class Justification {
    - correct : boolean
}

class Multimedia {

}

class Solution{
    - correct : boolean
    - type: SolutionType 
}

enum SolutionType {
    Open
    MultipleChoice
    ApplicationCode
}

class Answer {
    - correct : boolean
    - evaluated : boolean
}

EducationPlatform *--> "+" Teacher
EducationPlatform *--> "+" Student
EducationPlatform *--> Topic
EducationPlatform *--> Itinerary : predefined
EducationPlatform o--> "*" Itinerary : custom
EducationPlatform o--> Chat
Chat o--> "+" Excercise



Teacher ..> Chat
Student ..> Chat
Student o-->"*" Answer

Excercise <|-- Domain
Excercise <|-- Question 

Domain o-->"*" Application: requirements
Application -->"+" Concept
Domain o--> "*" Solution

Question -->"+" Concept
Question -->"*" Application
Question o-->"*" Answer
Question *--> StatementType
Question o--> "*" Solution
Solution *--> SolutionType
Solution o--> "?" Justification : correct = false

Teacher ..> Topic : editor
Teacher ..> Itinerary : editor
Student ...> Itinerary : editor
note left of Student
    Editor only
    for custom 
    itineraries
    end note
'Student ...> Custom : editor


Topic <|.. CompositeTopic
Topic <|.. SimpleTopic
CompositeTopic o--> "+" Topic

'Itinerary <|-- Custom
'Itinerary <|-- Predefined

Itinerary o--> "+" Topic
'Predefined o--> "+" Topic


SimpleTopic o--> "+" Concept
Topic o--> "+" Multimedia
Concept *--> "+" Definition : correct
Concept *--> "*" Definition : incorrect
Relation *-right-> RelationType
Concept *--> "*" Relation : origin

enum RelationType {
    Use
    Association
    Composition
    Inheritance
    Aggregation
} 

class Relation {
    - type : RelationType
}


Relation --> "+" Concept : target
Definition o-->"*" Justification :correct = false

'Justification o-->"+" Justification


Multimedia <|-- Podcast
Multimedia <|-- Video

Podcast o--> Text : transcript
Video o--> Text : transcript

Multimedia <|-- Text

Text -->"*" Concept

@enduml