@startuml
class Course
class Unit
class Topic
class Multimedia

Course *-->"n" Syllabus
Course *--> DefinitionDomain
Syllabus *-->"n" Topic
Topic o--> Unit

Unit o--> "n" Definition
Unit o--> "n" Multimedia

DefinitionDomain o--> Definition

Multimedia <|-- Video
Multimedia <|-- Podcast
Multimedia <|-- Image
Multimedia <|-- Document


@enduml