@startuml EducationPlatformDomain

EducationPlatform *--> "+" User
EducationPlatform *--> Topic
EducationPlatform *--> Itinerary : predefined
EducationPlatform o--> "*" Itinerary : custom
EducationPlatform *--> Chat

abstract User{
}

User <|-- Teacher
User <|-- Student
User *-->"+" Solution
User ..> Chat
User ..> Itinerary

class Teacher{
}

class Student{
}

class Chat{
}
Chat ..> "+" Topic

class Itinerary {
    - custom : boolean
    - topics : List<Topic>
}
Itinerary o--> "+" Topic

class Definition {
    - correct : boolean
}
Definition *--> "*" Justification:[!definition.correct]

class Justification {
    - correct : boolean
}

class Domain {
    - version : int
    - requirements : List<String>
}

abstract Exercise {
    - statement : String
    - solutions : List<Solution>
}
Exercise <|-down- Domain
Exercise <|-right- Question
Exercise *-->"+" Solution
Exercise o-->"*" Solution
Exercise ..> Solution : contrast

abstract Question{
    - statement : Statement
}
Question <|-- MultipleChoice
Question <|-- Cloze
Question <|-- Open

class Cloze{
    blankCount: int
}
  
class MultipleChoice{
}

class Solution{
    - correct : boolean
    - evaluated : boolean
    - Application : String
}
Solution *--> "*" Justification:[!solution.correct]

abstract Topic{
    - documents : List<Document>
}
Topic *-[#green]-> "*" Document
Topic <|-- CompositeTopic
Topic <|-- SimpleTopic

class SimpleTopic{
    - concepts : List<Concept>
    - exercises : List<Exercise>
}
SimpleTopic o--> "+" Concept
SimpleTopic *-[#red]- "*" Exercise

class CompositeTopic{
    - topics : List<Topic> 
}
CompositeTopic o--> "+" Topic

abstract Document{}
Document <|-- Audio
Document <|-- Video
Document <|-- Image
Document <|-- Text

class Concept{
    - exercises : List<Exercise>
    - relations : List<Relation>
}
Concept *-down-> "+" Definition : correct
Concept *-down-> "*" Definition : incorrect
Concept *-down-> "*" Relation
Concept o-down[#green]-> "*" Document
Concept o-down[#red]-> "*" Exercise

class Relation {
    - type : RelationType
    - origin : Concept
    - traget : Concept
}
Relation --> Concept : target
Relation *-down-> RelationType
Relation --> Concept : origin

enum RelationType {
    Use
    Association
    Composition
    Inheritance
    Aggregation
} 
@enduml