@startuml
class Course
class Module
class Unit
class Topic
class GroupTopic
class Multimedia

Course o--"n" Module
Module o--"n" Unit
Unit <|-- Topic
Unit <|-- GroupTopic
Topic o-- "n" DefinitionConceptPair
Topic o-- "n" Multimedia

@enduml