@startuml EducationPlatform
interface Topic{
    + getTableOfContents()
    + Edit()
    + Read()
}


class UnitaryTopic{
    - TableOfContents

}

class CompositeTopic{
    - topics : List<Topic> 
}

EducationPlatform *--> "+" Teacher
EducationPlatform *--> "+" Student
EducationPlatform *--> Topic
EducationPlatform o--> "+" Itinerary
EducationPlatform o--> Exercise
EducationPlatform o--> Asker

Exercise o--> DomainProblem
DomainProblem o--> Concept : solution

Teacher ..> Topic : Editor
Student ...> Topic : Reader

Topic <|.. CompositeTopic
Topic <|.. UnitaryTopic
CompositeTopic o--> "+" Topic

Itinerary <|-- Custom
Itinerary <|-- Predefined

Custom o--> "*" Topic
Predefined o--> "*" Topic


UnitaryTopic o--> "+" Concept
UnitaryTopic o--> "+" Multimedia
Concept *--> "+" Definition
Definition *--> "*" Relation
Relation <|-- Use
Relation <|-- Association
Relation <|-- Agregation
Relation <|-- Composition
Relation <|-- Inheritance

Relation --> Concept


Multimedia <|-- Podcast
Multimedia <|-- Video

Podcast o--> Document : transcript
Video o--> Document : transcript

Multimedia <|-- Document




@enduml