@startuml Educational Platfom Domain Model
!include LearningResource.puml

class EducationPlatform
abstract User
class Teacher
class Student

EducationPlatform *--> "n" User
EducationPlatform o--> LearningResource

User <|-- Teacher
User <|-- Student

@enduml