@startuml Educational Platfom Domain Model
!include EducationalContent.puml
!include EducationalResources.puml

class EducationPlatform
class User
class Teacher
class Student
class EducationalResources

EducationPlatform o-- "n" User
User <|-- Teacher
User <|-- Student
EducationPlatform o-- "n" EducationalContent
EducationPlatform o-- "n" EducationalResources

@enduml