@startuml EducationPlatformVocabulary
class EducationPlatform

class Student
class StudentGroup
class ConcreteStudent
class Teacher

'ojo diferentes nomenclaturas:  materia, tema, clase, etc
class Subject
class Course
class GroupTheme
class Theme
class Topic
class EducationalContent
class LEarningTopic
class StudyUnit


class EducationalResources
class Chat
class KnowledgeDataBase
class Classroom

class Test
class Question
class Answer
class Grade
class Evaluation

class Definition
class Concept

class Sample

class Multimedia
@enduml