@startuml
class EducationalContent
abstract Subject
class Course
class LearningUnit
class Topic
class Subtopic
Enum Content{
    Index
    Title
    Description
    ContentText
    Multimedia
    Vocabulary
    References
    Links
}

EducationalContent o--"n" Subject
Subject o--"n" Course
Course o--"n" LearningUnit
LearningUnit <|-- Topic
LearningUnit <|-- Subtopic
LearningUnit *-- Content
@enduml