@startuml EducationPlatform
class EducationPlatform
class Student
class Teacher
class GroupTheme
class Theme
class Chat
class Index
class KnowledgeDataBase
class ClassRoom
class Test
class Question
class Answer
class Definition
class Concept
class Sample
class Multimedia
@enduml