@startuml
!include Course.puml

class LearningResource
class Exercise
class CardTest
class NormalTest
class Exam

LearningResource o--> "n" Course
LearningResource o--> "n" Exercise
LearningResource o--> "n" Exam

LearningResource *--> Calendar

Exercise o-- "n" CardTest
CardTest ..>"n" DefinitionDomain

Exercise o--> "n" NormalTest

@enduml